import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  chooserSubtitleWrap: {
    marginTop: 4,
    marginBottom: 8, // further reduced for less space between tagline and buttons
    paddingHorizontal: 0,
    alignItems: 'center',
    width: '100%',
  },
  chooserContainer: {
    alignItems: 'center',
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    marginTop: 0, // raise card to top
    marginBottom: 'auto',
  },
  chooserPageBackground: {
    backgroundColor: 'rgba(255,255,255,0.10)',
  },
  chooserSubtitle: {
    fontSize: 25,
    lineHeight: 34,
    fontWeight: '700',
    marginTop: 22,
    marginBottom: 32,
    textAlign: 'center',
    color: '#232323', // slightly lighter than pure black
    textShadowColor: 'rgba(0,0,0,0.28)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 6,
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderRadius: 0,
    paddingHorizontal: 0,
    paddingVertical: 0,
    elevation: 0,
  },
  chooserCards: {
    width: '100%',
    maxWidth: 420,
    gap: 12,
  },
  chooserCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    paddingVertical: 15,
    paddingHorizontal: 18,
    borderWidth: 0,
    borderColor: 'transparent',
    borderRadius: 14,
    backgroundColor: '#fff',
    boxShadow: '0 2px 12px 0 #f3f4f688',
    elevation: 1,
  },
  chooserCardHover: {
    borderColor: '#FF8C66',
    boxShadow: '0 4px 10px 0 #0002',
    elevation: 2,
  },
  chooserIcon: {
    fontSize: 28,
    lineHeight: 34,
  },
  chooserCardTextWrap: {
    flex: 1,
    gap: 2,
  },
  chooserCardTitle: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '700',
    color: '#1F2937',
  },
  chooserCardTitleHover: {
    color: '#FF9F1C',
  },
  chooserCardBody: {
    fontSize: 14,
    lineHeight: 20,
    color: '#6B7280',
  },
  buttonPressed: {
    transform: [{ scale: 0.97 }],
    elevation: 4,
    shadowColor: '#FF9F1C',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    borderColor: '#FFEDD5',
    borderWidth: 1.5,
    backgroundColor: '#fff8f2',
  },
  chooserContentBox: {
    backgroundColor: 'rgba(243,244,246,0.97)',
    borderRadius: 22,
    paddingVertical: 40,
    paddingHorizontal: 32,
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 12px 32px 0 #0003',
    elevation: 16,
    borderWidth: 1.5,
    borderColor: '#E0E1E4',
    width: 440,
    maxWidth: '95%',
    alignSelf: 'center',
    transitionProperty: 'background, box-shadow, border-color, border-radius',
    transitionDuration: '180ms',
    transitionTimingFunction: 'ease-in-out',
  },
  screen: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  container: {
    flex: 1,
    paddingTop: 0,
    paddingHorizontal: 8,
    position: 'relative',
    overflow: 'hidden',
  },
  authCorner: {
    position: 'absolute',
    left: 10,
    zIndex: 3,
    elevation: 12,
  },
  authRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderRadius: 13,
    paddingVertical: 6,
    paddingHorizontal: 8,
    gap: 7,
  },
  authAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  authMeta: {
    maxWidth: 112,
  },
  authSignedText: {
    fontSize: 11,
    opacity: 0.72,
  },
  authName: {
    fontSize: 12,
    fontWeight: '600',
  },
  signInButton: {
    backgroundColor: 'rgba(66,133,244,0.94)',
    borderRadius: 10,
    paddingVertical: 7,
    paddingHorizontal: 10,
  },
  signInButtonHover: {
    backgroundColor: '#2F74D9',
  },
  signInText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '600',
  },
  signOutButton: {
    backgroundColor: '#EAF6FB',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  signOutButtonHover: {
    backgroundColor: '#D8EDF8',
  },
  signOutText: {
    color: '#0A7EA4',
    fontSize: 12,
    fontWeight: '600',
  },
  bgDogsLayer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  bgDogImage: {
    position: 'absolute',
    width: 200,
    height: 200,
    borderRadius: 20,
    opacity: 0.045,
  },
  bgDogYellow: {
    top: 60,
    left: -24,
    transform: [{ rotate: '-10deg' }],
  },
  bgDogBlack: {
    top: 180,
    right: -20,
    transform: [{ rotate: '8deg' }],
  },
  bgDogChocolate: {
    bottom: 34,
    left: 38,
    transform: [{ rotate: '-6deg' }],
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 12,
    zIndex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginTop: 32, // position card higher on screen
    paddingVertical: 18,
    paddingHorizontal: 0,
    width: '100%',
    maxWidth: 420,
  },
  titleWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    marginTop: -32,
  },
  titleBalanceSpacer: {
    width: 42,
  },
  titlePawCluster: {
    marginLeft: 2,
  },
  titlePawIcon: {
    width: 40,
    height: 40,
    marginTop: -2,
    transform: [{ translateY: -4 }],
  },
  title: {
    lineHeight: 30,
    flexShrink: 1,
    color: '#FF9F1C',
    marginBottom: 10, // tighter spacing below title
    marginTop: 0,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 19,
    fontWeight: '500',
    color: 'rgba(0,0,0,0.7)',
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 14,
    backgroundColor: 'transparent',
    paddingVertical: 0,
    paddingHorizontal: 0,
    borderRadius: 0,
    borderWidth: 0,
    elevation: 0,
    shadowOpacity: 0,
  },
  chooserSubtitle: {
    fontSize: 18,
    color: '#6B7280',
    marginBottom: 32,
    marginTop: 8,
    textAlign: 'center',
    fontWeight: '500',
    opacity: 0.75, // reduced opacity for less emphasis
  },
  chooserCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    paddingVertical: 18,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
    transitionProperty: 'transform, box-shadow',
    transitionDuration: '120ms',
    transitionTimingFunction: 'ease-in-out',
  },
});
