import { Platform, StyleSheet } from 'react-native';
import { DOGGYDEX_CORAL_RED, DOGGYDEX_ORANGE } from '../constants/theme';

export const quizStyles = StyleSheet.create({
  footer: {
    width: '100%',
    textAlign: 'center',
    paddingVertical: 12,
    fontSize: 14,
    color: '#888',
    backgroundColor: 'rgba(255,255,255,0.48)',
    position: 'absolute',
    bottom: 0,
    left: 0,
    zIndex: 9999,
    letterSpacing: 0.2,
  },
  dimmedCard: {
    opacity: 0.45,
  },
  timerPill: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    position: 'absolute',
    top: 16,
    right: 16,
    marginTop: 0,
    marginBottom: 0,
    ...(Platform.OS === 'web' ? { boxShadow: `0 2px 8px 0 ${DOGGYDEX_ORANGE}33` } : null),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 120,
  },
  breedPillLeft: {
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    paddingVertical: 4,
    paddingHorizontal: 4,
    paddingRight: 0,
    color: 'black',
    fontWeight: '400',
    borderWidth: 2,
    borderColor: '#FF8C66',
  },
  breedPillRight: {
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderRadius: 24,
    paddingVertical: 6,
    paddingHorizontal: 8,
    minWidth: 48,
    maxWidth: 280,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    borderWidth: 2,
    borderColor: '#FF8C66',
    marginLeft: 24,
    marginTop: 12,
    marginBottom: 8,
    ...(Platform.OS === 'web' ? { boxShadow: '0 2px 4px 0 #FF8C6622' } : null),
  },
  promptSmall: {
    fontSize: Platform.OS === 'web' ? 20 : 17.5,
    lineHeight: 20,
    textAlign: 'center',
    color: '#6B7280',
    marginTop: Platform.OS === 'web' ? 12 : 6,
    marginBottom: 4,
    fontWeight: '600',
  },
  promptLarge: {
    fontSize: Platform.OS === 'web' ? 23 : 35,
    lineHeight: Platform.OS === 'web' ? 31 : 39,
    textAlign: 'center',
    color: '#FF9F1C',
    marginTop: Platform.OS === 'web' ? 8 : 4,
    marginBottom: 0,
    fontWeight: '800',
  },
  gradientOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    paddingTop: 48,
    pointerEvents: 'none',
  },
  scoreHeartsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Platform.OS === 'web' ? 104 : 12,
    marginBottom: Platform.OS === 'web' ? 24 : 12,
    width: '100%',
  },
  scoreHeartsContainer: {
    backgroundColor: 'rgba(255,255,255,0.85)',
    borderRadius: 14,
    paddingVertical: Platform.OS === 'web' ? 12 : 10,
    paddingHorizontal: 16,
    marginTop: 0,
    marginBottom: 0,
    paddingBottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    ...(Platform.OS === 'web'
      ? { boxShadow: '0 6px 18px 0 #fff3' }
      : {
          shadowColor: '#111827',
          shadowOffset: { width: 0, height: 8 },
          shadowOpacity: 0.16,
          shadowRadius: 14,
          elevation: 6,
        }),
    width: '100%',
    maxWidth: 440,
    alignSelf: 'center',
  },
  heartsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 0,
  },
  heartsChip: {
    minWidth: 94,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  heartIcon: (active) => ({
    fontSize: Platform.OS === 'web' ? 20 : 24,
    fontWeight: '400',
    marginHorizontal: 4,
    color: active ? DOGGYDEX_CORAL_RED : '#D3D3D3',
    ...(Platform.OS === 'web' ? { textShadow: '0 1px 2px rgba(0,0,0,0.12)' } : null),
  }),
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingHorizontal: Platform.OS === 'web' ? 22 : 12,
    paddingTop: Platform.OS === 'web' ? 24 : 12,
    paddingBottom: 12,
    gap: 0,
    ...(Platform.OS === 'web'
      ? {
          backdropFilter: 'blur(2.5px) brightness(0.82)',
          WebkitBackdropFilter: 'blur(2.5px) brightness(0.82)',
        }
      : {}),
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 8,
    marginTop: 'auto',
    paddingBottom: 20,
  },
  loadingOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  loadingOverlayStrong: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    backgroundColor: 'rgba(10,14,20,0.28)',
    zIndex: 2600,
  },
  timerBlurOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 15,
    overflow: 'hidden',
  },
  timerBlurOverlayNative: {
    ...StyleSheet.absoluteFillObject,
  },
  timerBlurOverlayWeb: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.12)',
    backdropFilter: 'blur(16px)',
    WebkitBackdropFilter: 'blur(16px)',
  },
  timeoutMessageOverlay: {
    position: 'absolute',
    top: '34%',
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 40,
  },
  timeoutMessageText: {
    fontSize: Platform.OS === 'web' ? 32 : 30,
    fontWeight: '900',
    color: '#fff',
    textAlign: 'center',
    paddingVertical: 10,
    paddingHorizontal: 22,
    backgroundColor: 'rgba(30, 0, 0, 0.82)',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#fff',
    overflow: 'hidden',
    ...(Platform.OS === 'web'
      ? {
          textShadow: '0 5px 12px #FF2D55',
          boxShadow: '0 6px 12px #FF2D5588',
        }
      : {
          textShadowColor: '#FF2D55',
          textShadowOffset: { width: 0, height: 2 },
          textShadowRadius: 10,
          shadowColor: '#FF2D55',
          shadowOffset: { width: 0, height: 6 },
          shadowOpacity: 0.35,
          shadowRadius: 10,
          elevation: 8,
        }),
  },
  loadingCard: {
    width: '100%',
    maxWidth: 330,
    borderRadius: 16,
    paddingVertical: 18,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.95)',
    ...(Platform.OS === 'web'
      ? { boxShadow: '0 10px 24px rgba(17,24,39,0.16)' }
      : {
          shadowColor: '#111827',
          shadowOffset: { width: 0, height: 6 },
          shadowOpacity: 0.2,
          shadowRadius: 12,
          elevation: 8,
        }),
  },
  loadingTitle: {
    fontSize: 18,
    lineHeight: 22,
    color: '#111827',
    fontWeight: '800',
    textAlign: 'center',
  },
  loadingSubtitle: {
    fontSize: 13,
    lineHeight: 18,
    color: '#6B7280',
    fontWeight: '600',
    textAlign: 'center',
  },
  title: {
    lineHeight: 30,
    flexShrink: 1,
  },
  scoreText: {
    fontSize: 18,
    lineHeight: 24,
    opacity: 0.92,
  },
  prompt: {
    fontSize: 18,
    lineHeight: 28,
    textAlign: 'center',
    color: '#FF9F1C',
    marginTop: 0,
    marginBottom: 0,
    paddingTop: 44,
    paddingBottom: 0,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Platform.OS === 'web' ? 22 : 8,
    justifyContent: 'center',
    alignSelf: 'center',
    width: '100%',
    maxWidth: 600,
    paddingTop: Platform.OS === 'web' ? 6 : 10,
    paddingBottom: Platform.OS === 'web' ? 14 : 8,
  },
  card: {
    width: Platform.OS === 'web' ? '44%' : '48%',
    maxWidth: Platform.OS === 'web' ? 270 : 286,
    aspectRatio: 1,
    borderRadius: Platform.OS === 'web' ? 16 : 14,
    overflow: 'hidden',
    justifyContent: 'flex-end',
    borderWidth: Platform.OS === 'web' ? 1.5 : 2,
    borderColor: '#f0a84b',
    position: 'relative',
    ...(Platform.OS === 'web'
      ? {
          boxShadow: '0 10px 25px rgba(0,0,0,0.20), inset 0 2px 4px rgba(255,255,255,0.35)',
          transition: 'transform 120ms ease, box-shadow 120ms ease, border-width 120ms ease',
        }
      : {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 6 },
          shadowOpacity: 0.22,
          shadowRadius: 12,
          elevation: 6,
        }),
  },
  cardSlot: {
    width: Platform.OS === 'web' ? '44%' : '48%',
    maxWidth: Platform.OS === 'web' ? 270 : 286,
  },
  cardFill: {
    width: '100%',
    maxWidth: '100%',
  },
  imageFallback: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#E5E7EB',
    paddingHorizontal: 8,
  },
  imageFallbackText: {
    fontSize: 12,
    lineHeight: 16,
    color: '#374151',
    textAlign: 'center',
    fontWeight: '600',
  },
  mobileHeaderCard: {
    width: '100%',
    maxWidth: 440,
    alignSelf: 'center',
    borderRadius: 0,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderColor: 'transparent',
    marginBottom: 0,
    shadowColor: 'transparent',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  mobileStatsRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
    gap: 12,
  },
  mobileScoreWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mobileScoreLabel: {
    fontSize: 13,
    lineHeight: 18,
    color: '#374151',
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  mobileScoreValue: {
    fontSize: 34,
    lineHeight: 38,
    color: '#111827',
    fontWeight: '900',
  },
  mobileTimerChip: {
    minWidth: 74,
    borderRadius: 12,
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginRight: -4,
    backgroundColor: '#FFF7E9',
    borderWidth: 1,
    borderColor: '#FCD9A7',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  mobileTimerIcon: {
    fontSize: 14,
    lineHeight: 16,
  },
  mobileTimerValue: {
    fontSize: 22,
    lineHeight: 24,
    fontWeight: '800',
    color: '#FF9F1C',
  },
  mobileTimerCritical: {
    color: DOGGYDEX_CORAL_RED,
  },
  mobilePromptWrap: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mobileQuizStack: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    marginTop: 0,
    transform: [{ translateY: -34 }],
    paddingBottom: 20,
  },
  mobilePlusOneOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2400,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mobilePlusOneBubble: {
    minWidth: 52,
    borderRadius: 8,
    backgroundColor: 'rgba(255,159,28,0.34)',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    paddingVertical: 4,
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FFFFFF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.75,
    shadowRadius: 8,
    elevation: 8,
  },
  mobilePlusOneText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 1,
    textAlign: 'center',
  },
  mobileTopBackWrap: {
    width: '100%',
    maxWidth: 452,
    alignSelf: 'center',
    alignItems: 'flex-start',
    marginLeft: -2,
    marginBottom: 10,
  },
  mobileTopBackButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255,248,240,0.95)',
    borderWidth: 1,
    borderColor: 'rgba(216,180,148,0.78)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.16,
    shadowRadius: 8,
    elevation: 4,
  },
  mobileTopBackButtonPressed: {
    transform: [{ scale: 0.96 }],
  },
  mobileQuizCard: {
    width: '100%',
    maxWidth: 452,
    alignSelf: 'center',
    minHeight: 548,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.92)',
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.16,
    shadowRadius: 14,
    elevation: 5,
    overflow: 'hidden',
  },
  mobileGridCard: {
    width: '100%',
    maxWidth: 452,
    alignSelf: 'center',
    marginTop: -10,
    borderRadius: 0,
    paddingHorizontal: 8,
    paddingTop: 4,
    paddingBottom: 10,
    minHeight: 382,
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderColor: 'transparent',
    shadowColor: 'transparent',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  mobileGridPlaceholder: {
    width: '100%',
    minHeight: 350,
  },
  mobileCardCaption: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: 'rgba(17,24,39,0.52)',
  },
  mobileCardCaptionText: {
    fontSize: 11,
    lineHeight: 14,
    color: '#FFFFFF',
    textAlign: 'center',
    fontWeight: '700',
  },
  cardHover: {
    transform: [{ scale: 1.04 }],
    ...(Platform.OS === 'web' ? { boxShadow: '0 16px 35px rgba(0,0,0,0.25)' } : null),
    borderWidth: 3,
    borderColor: '#f0a84b',
  },
  cardPressed: {
    transform: [{ scale: 0.96 }],
  },
  wrongReveal: {
    borderWidth: 3,
    borderColor: 'red',
  },
  wrongBlur: {
    borderWidth: 3,
    borderColor: 'red',
    ...(Platform.OS === 'web'
      ? {
          filter: 'blur(2.5px) brightness(0.82)',
          WebkitFilter: 'blur(2.5px) brightness(0.82)',
        }
      : {}),
  },
  wrongTapOverlay: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 3,
    borderColor: '#FF3B30',
    borderRadius: Platform.OS === 'web' ? 16 : 14,
  },
  correctTapOverlay: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 4,
    borderColor: '#22C55E',
    borderRadius: Platform.OS === 'web' ? 16 : 14,
    ...(Platform.OS === 'web'
      ? { boxShadow: 'inset 0 0 0 1px rgba(255,255,255,0.32), 0 0 10px rgba(34,197,94,0.55)' }
      : {
          shadowColor: '#22C55E',
          shadowOffset: { width: 0, height: 0 },
          shadowOpacity: 0.5,
          shadowRadius: 8,
          elevation: 6,
        }),
  },
  image: {
    ...StyleSheet.absoluteFillObject,
    ...(Platform.OS === 'web' ? { objectFit: 'cover' } : null),
  },
  cardLabel: {
    fontSize: 12,
    lineHeight: 16,
    paddingVertical: 6,
    paddingHorizontal: 4,
    textAlign: 'center',
    width: '100%',
    backgroundColor: 'rgba(26, 32, 37, 0.52)',
    color: '#FFFFFF',
  },
  correctReveal: {
    transform: [{ scale: 1.06 }],
    zIndex: 2,
  },
  controls: {
    gap: 8,
    alignItems: 'center',
    marginTop: 2,
  },
  resultText: {
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
  },
  unlockText: {
    fontSize: 14,
    lineHeight: 20,
    color: 'green',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  unlockBanner: {
    width: '100%',
    maxWidth: 320,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#E9FBEA',
    borderWidth: 1,
    borderColor: '#80C783',
    gap: 2,
  },
  unlockTitle: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    textAlign: 'center',
    color: '#1F7A2E',
  },
  badgeBanner: {
    width: '100%',
    maxWidth: 320,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#FFF7DD',
    borderWidth: 1,
    borderColor: '#E3C15A',
  },
  badgeText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    textAlign: 'center',
    color: '#8A6A00',
  },
  nextButton: {
    width: '100%',
    maxWidth: 300,
    alignItems: 'center',
  },
  buttonPressed: {
    transform: [{ scale: 0.98 }],
  },
  nextButtonHover: {
    backgroundColor: '#F77777',
  },
  nextButtonLabel: {
    fontWeight: '600',
    textAlign: 'center',
    width: '100%',
  },
  switchLink: {
    alignSelf: 'flex-start',
    marginTop: 16,
    marginLeft: 10,
    borderRadius: 9,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'rgba(255,255,255,0.48)',
    minHeight: 32,
    minWidth: 95,
  },
  bottomBackWrap: {
    marginTop: 'auto',
    alignSelf: 'center',
    marginBottom: 56,
  },
  switchLinkHover: {
    backgroundColor: 'rgba(255,255,255,0.42)',
    transform: [{ translateX: -2 }],
  },
  switchLinkPressed: {
    transform: [{ scale: 0.99 }],
  },
  switchLinkText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '500',
    paddingTop: 3,
    color: '#4A2A1F',
    letterSpacing: 0.2,
    opacity: 0.8,
  },
  switchLinkTextHover: {
    color: '#cc6a44',
    textDecorationLine: 'underline',
    opacity: 1,
    fontWeight: '700',
  },
  switchLinkTextPressed: {
    color: '#3A2018',
  },
  hint: {
    fontSize: 14,
    lineHeight: 20,
    opacity: 0.85,
    textAlign: 'center',
    marginTop: 8,
  },
  chooseHint: {
    marginTop: 12,
  },
  centerGradientOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    pointerEvents: 'none',
  },
  grassBackground: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    pointerEvents: 'none',
  },
});
