import { Platform, StyleSheet } from 'react-native';
import { DOGGYDEX_CORAL_RED, DOGGYDEX_ORANGE } from '../constants/theme';
import { DoggyDexTheme } from '../constants/theme';

export const quizStyles = StyleSheet.create({
  unlockToastWrap: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: Platform.OS === 'web' ? 54 : 62,
    zIndex: 2450,
    elevation: 24,
    alignItems: 'center',
  },
  unlockToastCard: {
    width: '100%',
    maxWidth: 420,
    minHeight: 82,
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: '#D8B85A',
    backgroundColor: 'rgba(253, 255, 247, 0.98)',
    paddingVertical: 9,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    ...(Platform.OS === 'web'
      ? {
          boxShadow: '0 14px 30px rgba(31, 41, 55, 0.18), 0 0 0 1px rgba(255,255,255,0.88) inset',
        }
      : {
          shadowColor: '#1F2937',
          shadowOffset: { width: 0, height: 8 },
          shadowOpacity: 0.2,
          shadowRadius: 14,
          elevation: 12,
        }),
  },
  unlockToastIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#5FA777',
    borderWidth: 2,
    borderColor: '#F4D35E',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  unlockToastSparkle: {
    position: 'absolute',
    top: -5,
    right: -5,
  },
  unlockToastCopy: {
    flex: 1,
    minWidth: 0,
  },
  unlockToastTitle: {
    color: '#2F6B45',
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '900',
    letterSpacing: 0,
  },
  unlockToastBreed: {
    color: DoggyDexTheme.colors.text,
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '900',
    marginTop: 1,
  },
  breedMilestoneWrap: {
    position: 'absolute',
    left: 18,
    right: 18,
    bottom: Platform.OS === 'web' ? 66 : 74,
    zIndex: 2500,
    elevation: 28,
    alignItems: 'center',
  },
  breedMilestoneCard: {
    width: '100%',
    maxWidth: 390,
    minHeight: 168,
    borderRadius: DoggyDexTheme.radii.large,
    borderWidth: 2,
    borderColor: '#F4D35E',
    backgroundColor: 'rgba(253, 255, 247, 0.99)',
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    ...(Platform.OS === 'web'
      ? {
          boxShadow: '0 18px 42px rgba(31, 41, 55, 0.24), 0 0 0 1px rgba(255,255,255,0.92) inset',
        }
      : {
          shadowColor: '#1F2937',
          shadowOffset: { width: 0, height: 10 },
          shadowOpacity: 0.24,
          shadowRadius: 18,
          elevation: 14,
        }),
  },
  breedMilestoneImageWrap: {
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: '#5FA777',
    borderWidth: 3,
    borderColor: '#F4D35E',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    marginBottom: 9,
  },
  breedMilestoneImage: {
    width: '100%',
    height: '100%',
  },
  breedMilestoneCopy: {
    width: '100%',
    alignItems: 'center',
  },
  breedMilestoneTitle: {
    color: '#2F6B45',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '900',
    textAlign: 'center',
    letterSpacing: 0,
  },
  breedMilestoneBreed: {
    color: DoggyDexTheme.colors.text,
    fontSize: 22,
    lineHeight: 26,
    fontWeight: '900',
    textAlign: 'center',
    marginTop: 2,
  },
  breedMilestoneSparkleLeft: {
    position: 'absolute',
    top: 15,
    left: 18,
  },
  breedMilestoneSparkleRight: {
    position: 'absolute',
    top: 24,
    right: 24,
  },
  footer: {
    width: '100%',
    textAlign: 'center',
    paddingVertical: 12,
    fontSize: 14,
    color: '#888',
    backgroundColor: 'rgba(255,255,255,0.48)',
    position: 'absolute',
    bottom: 0,
    left: 0,
    zIndex: 9999,
    letterSpacing: 0.2,
  },
  dimmedCard: {
    opacity: 0.45,
  },
  gameOverRewardFlow: {
    width: '100%',
    gap: 8,
    marginTop: -4,
    marginBottom: 4,
  },
  gameOverXpMini: {
    width: '100%',
    borderRadius: 16,
    backgroundColor: '#FFF8EC',
    borderWidth: 1.5,
    borderColor: DoggyDexTheme.colors.gold,
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 6,
  },
  gameOverMiniLabel: {
    color: DoggyDexTheme.colors.textSecondary,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  gameOverXpHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  gameOverLevelUp: {
    color: '#2F6B45',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.35,
  },
  gameOverXpMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  gameOverLevelPill: {
    color: DoggyDexTheme.colors.text,
    fontSize: 15,
    lineHeight: 19,
    fontWeight: '900',
  },
  gameOverXpTotals: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
    gap: 6,
    flexShrink: 1,
  },
  gameOverXpTotal: {
    color: DoggyDexTheme.colors.textSecondary,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '800',
  },
  gameOverXpValue: {
    color: DoggyDexTheme.colors.primary,
    fontSize: 15,
    lineHeight: 19,
    fontWeight: '900',
  },
  gameOverXpTrack: {
    width: '100%',
    height: 11,
    borderRadius: 999,
    backgroundColor: '#F3DEC2',
    overflow: 'hidden',
  },
  gameOverXpFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: DoggyDexTheme.colors.primary,
  },
  gameOverXpSub: {
    color: DoggyDexTheme.colors.textSecondary,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '800',
    textAlign: 'right',
  },
  gameOverUnlockList: {
    width: '100%',
    gap: 6,
  },
  gameOverUnlockTile: {
    width: '100%',
    minHeight: 58,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: DoggyDexTheme.colors.border,
    backgroundColor: 'rgba(253,255,247,0.98)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingVertical: 7,
    paddingHorizontal: 9,
  },
  gameOverCoatUnlockTile: {
    backgroundColor: 'rgba(253,255,247,0.98)',
  },
  gameOverBreedUnlockTile: {
    borderWidth: 1.5,
    borderColor: DoggyDexTheme.colors.gold,
    backgroundColor: '#FFF8E5',
    shadowColor: DoggyDexTheme.colors.gold,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 2,
  },
  gameOverUnlockImageWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: '#5FA777',
    borderWidth: 1.5,
    borderColor: DoggyDexTheme.colors.gold,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gameOverBreedImageWrap: {
    borderWidth: 2,
    backgroundColor: '#D39B2A',
  },
  gameOverUnlockImage: {
    width: '100%',
    height: '100%',
  },
  gameOverUnlockCopy: {
    flex: 1,
    minWidth: 0,
  },
  gameOverUnlockTitle: {
    color: '#2F6B45',
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  gameOverBreedUnlockTitle: {
    color: '#8A5A00',
    letterSpacing: 0.25,
  },
  gameOverBreedSparkles: {
    position: 'absolute',
    right: 8,
    top: 7,
  },
  gameOverUnlockName: {
    color: DoggyDexTheme.colors.text,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '900',
  },
  gameOverRewardEmpty: {
    width: '100%',
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: DoggyDexTheme.colors.border,
    backgroundColor: '#FFF8EC',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  gameOverRewardEmptyText: {
    color: DoggyDexTheme.colors.textSecondary,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
    textAlign: 'center',
  },
  gameOverSummaryCard: {
    width: '100%',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: DoggyDexTheme.colors.gold,
    backgroundColor: 'rgba(253,255,247,0.98)',
    paddingVertical: 10,
    paddingHorizontal: 10,
    gap: 7,
  },
  gameOverIncredibleCard: {
    borderColor: '#B77AF3',
  },
  gameOverSummaryTitle: {
    color: DoggyDexTheme.colors.primary,
    fontSize: 17,
    lineHeight: 21,
    fontWeight: '900',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  gameOverIncredibleCount: {
    color: DoggyDexTheme.colors.text,
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '900',
    textAlign: 'center',
    marginTop: -5,
  },
  gameOverRewardChips: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  gameOverRewardChip: {
    borderRadius: 999,
    backgroundColor: '#FFF1D6',
    borderWidth: 1,
    borderColor: '#F4D35E',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 5,
    paddingHorizontal: 8,
  },
  gameOverRewardChipText: {
    color: DoggyDexTheme.colors.text,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '900',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  gameOverPreviewRow: {
    width: '100%',
    gap: 6,
  },
  gameOverUnlockViewport: {
    width: '100%',
    maxHeight: 224,
    overflow: 'hidden',
  },
  gameOverUnlockSeparator: {
    height: 6,
  },
  gameOverPreviewGrid: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    justifyContent: 'center',
  },
  gameOverPreviewImageWrap: {
    width: 44,
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: DoggyDexTheme.colors.gold,
    overflow: 'hidden',
    backgroundColor: DoggyDexTheme.colors.surface,
  },
  gameOverPreviewImage: {
    width: '100%',
    height: '100%',
  },
  gameOverMoreTile: {
    alignSelf: 'center',
    minWidth: 82,
    minHeight: 34,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#B77AF3',
    backgroundColor: '#F4E8FF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  gameOverMoreButton: {
    alignSelf: 'center',
    minHeight: 32,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: DoggyDexTheme.colors.gold,
    backgroundColor: '#FFF1D6',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    paddingVertical: 5,
    paddingHorizontal: 11,
    marginTop: -1,
  },
  gameOverMoreButtonPressed: {
    opacity: 0.8,
    transform: [{ scale: 0.98 }],
  },
  gameOverMoreText: {
    color: DoggyDexTheme.colors.textSecondary,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '900',
  },
  gameOverDoggyDexButton: {
    alignSelf: 'center',
    borderRadius: 999,
    backgroundColor: DoggyDexTheme.colors.primary,
    borderWidth: 1,
    borderColor: DoggyDexTheme.colors.gold,
    paddingVertical: 7,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  gameOverDoggyDexButtonPressed: {
    transform: [{ scale: 0.97 }],
  },
  gameOverDoggyDexText: {
    color: '#FFFFFF',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '900',
  },
  gameOverPreloadText: {
    color: DoggyDexTheme.colors.textMuted,
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  timerPill: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    position: 'absolute',
    top: 16,
    right: 16,
    marginTop: 0,
    marginBottom: 0,
    ...(Platform.OS === 'web' ? { boxShadow: `0 2px 8px 0 ${DOGGYDEX_ORANGE}33` } : null),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 120,
  },
  breedPillLeft: {
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    paddingVertical: 4,
    paddingHorizontal: 4,
    paddingRight: 0,
    color: 'black',
    fontWeight: '400',
    borderWidth: 2,
    borderColor: '#FF8C66',
  },
  breedPillRight: {
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderRadius: 24,
    paddingVertical: 6,
    paddingHorizontal: 8,
    minWidth: 48,
    maxWidth: 280,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    borderWidth: 2,
    borderColor: '#FF8C66',
    marginLeft: 24,
    marginTop: 12,
    marginBottom: 8,
    ...(Platform.OS === 'web' ? { boxShadow: '0 2px 4px 0 #FF8C6622' } : null),
  },
  promptSmall: {
    fontSize: Platform.OS === 'web' ? 20 : 17.5,
    lineHeight: 20,
    textAlign: 'center',
    color: '#6B7280',
    marginTop: Platform.OS === 'web' ? 12 : 6,
    marginBottom: 4,
    fontWeight: '600',
  },
  promptLarge: {
    fontSize: Platform.OS === 'web' ? 23 : 35,
    lineHeight: Platform.OS === 'web' ? 31 : 39,
    textAlign: 'center',
    color: '#FF9F1C',
    marginTop: Platform.OS === 'web' ? 8 : 4,
    marginBottom: 0,
    fontWeight: '800',
  },
  gradientOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    paddingTop: 48,
    pointerEvents: 'none',
  },
  scoreHeartsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Platform.OS === 'web' ? 104 : 12,
    marginBottom: Platform.OS === 'web' ? 24 : 12,
    width: '100%',
  },
  scoreHeartsContainer: {
    backgroundColor: 'rgba(255,246,232,0.96)',
    borderRadius: DoggyDexTheme.radii.large,
    paddingVertical: Platform.OS === 'web' ? 12 : 10,
    paddingHorizontal: 16,
    marginTop: 0,
    marginBottom: 0,
    paddingBottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    ...(Platform.OS === 'web'
      ? { boxShadow: '0 6px 18px 0 #fff3' }
      : {
          ...DoggyDexTheme.shadow,
        }),
    width: '100%',
    maxWidth: 440,
    alignSelf: 'center',
  },
  heartsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 0,
  },
  heartsChip: {
    minWidth: 94,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  heartIcon: (active) => ({
    fontSize: Platform.OS === 'web' ? 20 : 24,
    fontWeight: '400',
    marginHorizontal: 4,
    color: active ? DOGGYDEX_CORAL_RED : '#D3D3D3',
    ...(Platform.OS === 'web' ? { textShadow: '0 1px 2px rgba(0,0,0,0.12)' } : null),
  }),
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingHorizontal: Platform.OS === 'web' ? 22 : 12,
    paddingTop: Platform.OS === 'web' ? 4 : 0,
    paddingBottom: 12,
    gap: 0,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 8,
    marginTop: 'auto',
    paddingBottom: 20,
  },
  loadingOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  loadingOverlayStrong: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    backgroundColor: 'rgba(10,14,20,0.28)',
    zIndex: 2600,
  },
  timerBlurOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 15,
    overflow: 'hidden',
  },
  timerBlurOverlayNative: {
    ...StyleSheet.absoluteFillObject,
  },
  timerBlurOverlayWeb: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.12)',
    backdropFilter: 'blur(16px)',
    WebkitBackdropFilter: 'blur(16px)',
  },
  timeoutMessageOverlay: {
    position: 'absolute',
    top: '30%',
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 40,
  },
  timeoutMessageText: {
    fontSize: Platform.OS === 'web' ? 32 : 30,
    fontWeight: '900',
    color: '#fff',
    textAlign: 'center',
    paddingVertical: 10,
    paddingHorizontal: 22,
    backgroundColor: 'rgba(30, 0, 0, 0.82)',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#fff',
    overflow: 'hidden',
    ...(Platform.OS === 'web'
      ? {
          textShadow: '0 5px 12px #FF2D55',
          boxShadow: '0 6px 12px #FF2D5588',
        }
      : {
          textShadowColor: '#FF2D55',
          textShadowOffset: { width: 0, height: 2 },
          textShadowRadius: 10,
          shadowColor: '#FF2D55',
          shadowOffset: { width: 0, height: 6 },
          shadowOpacity: 0.35,
          shadowRadius: 10,
          elevation: 8,
        }),
  },
  loadingCard: {
    width: '100%',
    maxWidth: 330,
    borderRadius: 16,
    paddingVertical: 18,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.95)',
    ...(Platform.OS === 'web'
      ? { boxShadow: '0 10px 24px rgba(17,24,39,0.16)' }
      : {
          shadowColor: '#111827',
          shadowOffset: { width: 0, height: 6 },
          shadowOpacity: 0.2,
          shadowRadius: 12,
          elevation: 8,
        }),
  },
  loadingTitle: {
    fontSize: 18,
    lineHeight: 22,
    color: '#111827',
    fontWeight: '800',
    textAlign: 'center',
  },
  loadingSubtitle: {
    fontSize: 13,
    lineHeight: 18,
    color: '#6B7280',
    fontWeight: '600',
    textAlign: 'center',
  },
  title: {
    lineHeight: 30,
    flexShrink: 1,
  },
  scoreText: {
    fontSize: 18,
    lineHeight: 24,
    opacity: 0.92,
  },
  prompt: {
    fontSize: 18,
    lineHeight: 28,
    textAlign: 'center',
    color: '#FF9F1C',
    marginTop: 0,
    marginBottom: 0,
    paddingTop: 44,
    paddingBottom: 0,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Platform.OS === 'web' ? 22 : 8,
    justifyContent: 'center',
    alignSelf: 'center',
    width: '100%',
    maxWidth: 600,
    paddingTop: Platform.OS === 'web' ? 6 : 10,
    paddingBottom: Platform.OS === 'web' ? 14 : 8,
  },
  card: {
    width: Platform.OS === 'web' ? '44%' : '48%',
    maxWidth: Platform.OS === 'web' ? 270 : 286,
    aspectRatio: 1,
    borderRadius: DoggyDexTheme.radii.medium,
    overflow: 'hidden',
    justifyContent: 'flex-end',
    borderWidth: Platform.OS === 'web' ? 1.5 : 2,
    borderColor: DoggyDexTheme.colors.gold,
    position: 'relative',
    backgroundColor: DoggyDexTheme.colors.surface,
    ...(Platform.OS === 'web'
      ? {
          boxShadow: '0 10px 25px rgba(0,0,0,0.20), inset 0 2px 4px rgba(255,255,255,0.35)',
          transition: 'transform 120ms ease, box-shadow 120ms ease, border-width 120ms ease',
        }
      : {
          ...DoggyDexTheme.shadow,
        }),
  },
  cardSlot: {
    width: Platform.OS === 'web' ? '44%' : '48%',
    maxWidth: Platform.OS === 'web' ? 270 : 286,
  },
  cardFill: {
    width: '100%',
    maxWidth: '100%',
  },
  imageFallback: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#E5E7EB',
    paddingHorizontal: 8,
  },
  imageFallbackText: {
    fontSize: 12,
    lineHeight: 16,
    color: DoggyDexTheme.colors.textSecondary,
    textAlign: 'center',
    fontWeight: '600',
  },
  mobileHeaderCard: {
    width: '100%',
    maxWidth: 440,
    alignSelf: 'center',
    borderRadius: 0,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderColor: 'transparent',
    marginBottom: 0,
    shadowColor: 'transparent',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  mobileStatsRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
    gap: 12,
  },
  mobileScoreWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  mobileScoreLabel: {
    fontSize: 13,
    lineHeight: 18,
    color: '#374151',
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  mobileScoreValue: {
    fontSize: 34,
    lineHeight: 38,
    color: DoggyDexTheme.colors.text,
    fontWeight: '900',
  },
  mobileScoreGlow: {
    position: 'absolute',
    top: 5,
    left: -7,
    right: -7,
    bottom: 3,
    borderRadius: 999,
    backgroundColor: 'rgba(244,211,94,0.42)',
    shadowColor: DoggyDexTheme.colors.gold,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.75,
    shadowRadius: 10,
    elevation: 3,
  },
  webScoreGlow: {
    position: 'absolute',
    top: 5,
    left: -8,
    right: -8,
    bottom: 2,
    borderRadius: 999,
    backgroundColor: 'rgba(244,211,94,0.38)',
    boxShadow: '0 0 12px rgba(244,211,94,0.85)',
  },
  mobileTimerChip: {
    minWidth: 74,
    borderRadius: DoggyDexTheme.radii.small,
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginRight: -4,
    backgroundColor: DoggyDexTheme.colors.surface,
    borderWidth: 1,
    borderColor: DoggyDexTheme.colors.gold,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  mobileTimerChipCritical: {
    minWidth: 86,
    paddingVertical: 8,
    backgroundColor: '#2B0710',
    borderWidth: 2,
    borderColor: DOGGYDEX_CORAL_RED,
    ...(Platform.OS === 'web'
      ? {
          boxShadow: '0 0 18px rgba(215, 38, 61, 0.65), 0 0 3px #fff inset',
        }
      : {
          shadowColor: DOGGYDEX_CORAL_RED,
          shadowOffset: { width: 0, height: 0 },
          shadowOpacity: 0.45,
          shadowRadius: 10,
          elevation: 8,
        }),
  },
  mobileTimerIcon: {
    fontSize: 14,
    lineHeight: 16,
  },
  mobileTimerValue: {
    fontSize: 22,
    lineHeight: 24,
    fontWeight: '800',
    color: DoggyDexTheme.colors.primary,
  },
  mobileTimerCritical: {
    color: '#FFFFFF',
    fontSize: 31,
    lineHeight: 35,
    fontWeight: '900',
    textShadowColor: DOGGYDEX_CORAL_RED,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },
  mobilePromptWrap: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mobileQuizStack: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    marginTop: 0,
    transform: [{ translateY: -34 }],
    paddingBottom: 20,
  },
  mobilePlusOneOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2400,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 128,
  },
  mobilePlusOneBubble: {
    minWidth: 68,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 249, 232, 0.98)',
    borderWidth: 1.5,
    borderColor: DoggyDexTheme.colors.gold,
    paddingVertical: 3,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.16,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 20,
  },
  mobilePlusOneText: {
    color: '#2F6B45',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '900',
    letterSpacing: 0,
    textAlign: 'center',
  },
  mobileTopBackWrap: {
    width: '100%',
    maxWidth: 452,
    alignSelf: 'center',
    alignItems: 'flex-start',
    marginLeft: -2,
    marginBottom: 10,
  },
  mobileTopBackButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255,253,247,0.96)',
    borderWidth: 1,
    borderColor: DoggyDexTheme.colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    ...DoggyDexTheme.shadow,
  },
  mobileTopBackButtonPressed: {
    transform: [{ scale: 0.96 }],
  },
  mobileQuizCard: {
    width: '100%',
    maxWidth: 452,
    alignSelf: 'center',
    minHeight: 548,
    borderRadius: DoggyDexTheme.radii.large,
    backgroundColor: 'rgba(255,246,232,0.96)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.92)',
    ...DoggyDexTheme.shadow,
    overflow: 'hidden',
  },
  mobileGridCard: {
    width: '100%',
    maxWidth: 452,
    alignSelf: 'center',
    marginTop: -10,
    borderRadius: 0,
    paddingHorizontal: 8,
    paddingTop: 4,
    paddingBottom: 10,
    minHeight: 382,
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderColor: 'transparent',
    shadowColor: 'transparent',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  mobileGridPlaceholder: {
    width: '100%',
    minHeight: 350,
  },
  mobileCardCaption: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: 'rgba(17,24,39,0.52)',
  },
  mobileCardCaptionText: {
    fontSize: 11,
    lineHeight: 14,
    color: '#FFFFFF',
    textAlign: 'center',
    fontWeight: '700',
  },
  cardHover: {
    transform: [{ scale: 1.04 }],
    ...(Platform.OS === 'web' ? { boxShadow: '0 16px 35px rgba(0,0,0,0.25)' } : null),
    borderWidth: 3,
    borderColor: DoggyDexTheme.colors.gold,
  },
  cardPressed: {
    transform: [{ scale: 0.98 }],
  },
  wrongReveal: {
    borderWidth: 3,
    borderColor: DoggyDexTheme.colors.error,
  },
  wrongBlur: {
    borderWidth: 2,
    borderColor: DoggyDexTheme.colors.error,
    ...(Platform.OS === 'web'
      ? {
          filter: 'brightness(0.9)',
          WebkitFilter: 'brightness(0.9)',
        }
      : {}),
  },
  wrongTapOverlay: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 3,
    borderColor: DoggyDexTheme.colors.error,
    borderRadius: DoggyDexTheme.radii.medium,
  },
  correctTapOverlay: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 4,
    borderColor: DoggyDexTheme.colors.success,
    borderRadius: DoggyDexTheme.radii.medium,
    ...(Platform.OS === 'web'
      ? { boxShadow: 'inset 0 0 0 1px rgba(255,255,255,0.32), 0 0 10px rgba(34,197,94,0.55)' }
      : {
          shadowColor: '#22C55E',
          shadowOffset: { width: 0, height: 0 },
          shadowOpacity: 0.5,
          shadowRadius: 8,
          elevation: 6,
        }),
  },
  wrongToast: {
    position: 'absolute',
    top: Platform.OS === 'web' ? 68 : 82,
    alignSelf: 'center',
    zIndex: 2600,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(232,75,75,0.94)',
    paddingVertical: 7,
    paddingHorizontal: 12,
    shadowColor: DoggyDexTheme.colors.text,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  wrongToastText: {
    color: '#FFFFFF',
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '900',
  },
  image: {
    ...StyleSheet.absoluteFillObject,
    ...(Platform.OS === 'web' ? { objectFit: 'cover' } : null),
  },
  cardLabel: {
    fontSize: 12,
    lineHeight: 16,
    paddingVertical: 6,
    paddingHorizontal: 4,
    textAlign: 'center',
    width: '100%',
    backgroundColor: 'rgba(26, 32, 37, 0.52)',
    color: '#FFFFFF',
  },
  correctReveal: {
    transform: [{ scale: 1.04 }],
    zIndex: 2,
  },
  controls: {
    gap: 8,
    alignItems: 'center',
    marginTop: 2,
  },
  resultText: {
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
  },
  unlockText: {
    fontSize: 14,
    lineHeight: 20,
    color: 'green',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  unlockBanner: {
    width: '100%',
    maxWidth: 320,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#E9FBEA',
    borderWidth: 1,
    borderColor: '#80C783',
    gap: 2,
  },
  unlockTitle: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    textAlign: 'center',
    color: '#1F7A2E',
  },
  badgeBanner: {
    width: '100%',
    maxWidth: 320,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#FFF7DD',
    borderWidth: 1,
    borderColor: '#E3C15A',
  },
  badgeText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    textAlign: 'center',
    color: '#8A6A00',
  },
  nextButton: {
    width: '100%',
    maxWidth: 300,
    alignItems: 'center',
  },
  buttonPressed: {
    transform: [{ scale: 0.98 }],
  },
  nextButtonHover: {
    backgroundColor: '#F77777',
  },
  nextButtonLabel: {
    fontWeight: '600',
    textAlign: 'center',
    width: '100%',
  },
  switchLink: {
    alignSelf: 'flex-start',
    marginTop: 16,
    marginLeft: 10,
    borderRadius: 9,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'rgba(255,255,255,0.48)',
    minHeight: 32,
    minWidth: 95,
  },
  bottomBackWrap: {
    marginTop: 'auto',
    alignSelf: 'center',
    marginBottom: 56,
  },
  switchLinkHover: {
    backgroundColor: 'rgba(255,255,255,0.42)',
    transform: [{ translateX: -2 }],
  },
  switchLinkPressed: {
    transform: [{ scale: 0.99 }],
  },
  switchLinkText: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '500',
    paddingTop: 3,
    color: '#4A2A1F',
    letterSpacing: 0.2,
    opacity: 0.8,
  },
  switchLinkTextHover: {
    color: '#cc6a44',
    textDecorationLine: 'underline',
    opacity: 1,
    fontWeight: '700',
  },
  switchLinkTextPressed: {
    color: '#3A2018',
  },
  hint: {
    fontSize: 14,
    lineHeight: 20,
    opacity: 0.85,
    textAlign: 'center',
    marginTop: 8,
  },
  chooseHint: {
    marginTop: 12,
  },
  centerGradientOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    pointerEvents: 'none',
  },
  grassBackground: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    pointerEvents: 'none',
  },
});
